name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: olafurpg/setup-scala@v12

      - name: Cache SBT coursier cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/coursier/v1
          key: sbt-coursier-cache

      - name: Scalafmt
        run: sbt scalafmtAll scalafmtSbt

      - name: Tests
        run: sbt scripted
